# Generated by Django 5.2.4 on 2025-07-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_registration_email_registration_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
